name: Docs
on: push

jobs:
  openapi:
    name: OpenAPI
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: volta-cli/action@v1.7.0
      - name: Build document
        run: yarn doc:build
      - if: github.ref == 'refs/heads/master'
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
