name: Test
on: [push, pull_request]

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: volta-cli/action@v1.7.0
      - name: Cache NPM
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-cache-v1
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
